id: IEE154221
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T18:10:21+00:00'
last_modified: '2022-06-07T22:39:32.105472+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1JM1
  title: གསུང་རྩོམ། ཚེ་བརྟན་ཕུན་ཚོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A1F4:
      image_group_id: I00KG010259
      title: ''
      total_pages: 449
      order: 1
      base_file: A1F4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
