id: P004407
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:18:55.880444
source_metadata:
  id: bdr:W1JM1
  title: གསུང་རྩོམ། ཚེ་བརྟན་ཕུན་ཚོགས
  author: ''
  volumes:
    5be090d41ebe456eb78513b661e23650:
      image_group_id: I00KG010259
      title: ''
      volume_number: 1
      total_pages: 449
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
